# Generated by Django 2.2.3 on 2019-08-29 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='phnno',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
