# Generated by Django 2.2.3 on 2019-08-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_community', '0002_adduser_phnno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='phnno',
        ),
    ]
